from __future__ import annotations

from typing import Any, Iterator, Optional, Protocol, Tuple, runtime_checkable


@runtime_checkable
class ModulePackProtocol(Protocol):
    def __init__(self, **kwargs): ...
    def __getitem__(self, key: str) -> Any: ...
    def get(self, name: str) -> Any: ...
    def keys(self) -> Iterator[str]: ...
    def items(self) -> Iterator[Tuple[str, Any]]: ...
    def load_state_dict(self, path): ...
    def save_state_dict(self, path): ...
    @property
    def _fields(self): ...


@runtime_checkable
class ModuleProtocol(Protocol):
    """ """

    backend: str

    def __call__(self, embedding: Any, carry: Any = None, **kwargs: Any) -> Tuple[Any, Any]: ...

    def forward(self, embedding: Any, carry: Any = None, **kwargs: Any) -> Tuple[Any, Any]: ...

    def reset(self): ...
